### LINKS
# Mini media player - https://github.com/kalkih/mini-media-player
# Button Entity Row - https://github.com/custom-cards/button-entity-row

    

title: Home

resources:
  - url: /local/plugins/tracker-card.js?v=1.2.5
    type: js
  - url: 'https://unpkg.com/moment@2.22.2/moment.js'
    type: js
  - url: /local/plugins/card-modder.js?v=f3d96f
    type: js
  - url: /local/plugins/layout-card.js?v=e0ec2f
    type: js
  - url: /local/plugins/button-entity-row.js
    type: js
  - url: /local/plugins/mini-media-player-bundle.js?v=1.1.0
    type: module
  - url: /local/plugins/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/plugins/slider-entity-row.js?v1
    type: js
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /local/plugins/gap-card.js?v1
    type: js
  - url: /local/plugins/vertical-stack-in-card.js?v0.1.2
    type: js
  - url: /local/plugins/card-tools.js?v2
    type: js
  - url: /local/plugins/popup-card.js?v3
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /local/plugins/fold-entity-row.js
    type: js
  - url: /local/plugins/state-switch.js
    type: js
  - url: /customcards/github/maykar/lovelace-swipe-navigation.js?track=true
    type: js
  - url: /customcards/github/custom-cards/atomic-calendar.js?v0.1
    type: module
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.5/dist/spotify-card.umd.js    

views:

  - !include lovelace/00_home_view.yaml

  - !include lovelace/01_living_room_view.yaml

  - !include lovelace/02_alarm_view.yaml

  - !include lovelace/07_kitchen_view.yaml

  - !include lovelace/03_bedroom_view.yaml

  - !include lovelace/04_backend_view.yaml

  - !include lovelace/09_media_view.yaml

  - !include lovelace/08_tv_view.yaml

  #- !include lovelace/05_remote_view.yaml

  - !include lovelace/06_test_view.yaml

